### ISSUE TITLE
Martingale

### ISSUE THREAD

**Issue by krakengamerhd** [TheonlyIcebear/Bloxflip-Smart-Bet#13]
when you open martingale what is it supposed to do once you downloaded the pip requirement

**Comment by TheonlyIcebear** [comment]
What's the question? You run it.

**Comment by krakengamerhd** [comment]
does it like immediately start betting

**Comment by krakengamerhd** [comment]
because mine just opens then closes

**Comment by TheonlyIcebear** [comment]
I found an error, it's now fixed
