### ISSUE TITLE
issue bc of balance

### ISSUE THREAD

**Issue by Unetass** [TheonlyIcebear/Bloxflip-Smart-Bet#15]
File "C:\Bloxflip-Smart-Bet-main\Martingale.py", line 209, in sendBets
    balance = float(browser.find_element_by_css_selector(".MuiBox-root.jss220.jss44").text)
ValueError: could not convert string to float: '1,726.00'

**Comment by TheonlyIcebear** [comment]
Oh I see your balance had a comma in it preventing it from being turned into a number. I will fix this rn

**Comment by TheonlyIcebear** [comment]
Ok it's fixed
