### ISSUE TITLE
Issue because of my balance

### ISSUE THREAD

**Issue by F8SDFSJ8** [TheonlyIcebear/Bloxflip-Smart-Bet#16]
Traceback (most recent call last):
  File "C:\Users\Jettr\Desktop\Bloxflip-Smart-Bet-main\Martingale.py", line 209, in sendBets
    balance = float(browser.find_element_by_css_selector(".MuiBox-root.jss220.jss44").text.replace(',', ''))
ValueError: could not convert string to float: ''

Please fix

**Comment by TheonlyIcebear** [comment]
Fixed I believe. Your authorization may have been invalid
