### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by MrSiko** [TheonlyIcebear/Bloxflip-Smart-Bet#17]
when i open it i have the right token and it opens but it isn't logged in and it refreshes automatically and gets logged in but while it's refreshing the bot says that it's not the right token when it logs in so if you could slow down the check time that would help alot

**Comment by TheonlyIcebear** [comment]
Yeah I know it was a error related to the name of the css class for your balance on bloxflip. It is fixed now

**Comment by MrSiko** [comment]
multiplier aint working now
