### ISSUE TITLE
loss issue

### ISSUE THREAD

**Issue by Liays-eng** [TheonlyIcebear/Bloxflip-Smart-Bet#19]
loss isn't detected when it instantly crashes at x1.00, x1.01 or 1.02 (and it also doesn't bet in the round right after the crash)

**Comment by TheonlyIcebear** [comment]
Not sure why this would happen. But I'm trying to recreate the bug rn

**Comment by TheonlyIcebear** [comment]
Are you sure you didn't run out of robux?

**Comment by TheonlyIcebear** [comment]
After thinking about it I realized the program isn't refreshing the tab with the information on the games quickly enough and since the small crashpoint games last very shortly the program simply doesn't see the game. I've fixed the issue now
