### ISSUE TITLE
The StreakBased version doesn't work even after the 30 games required for the diagnostic data

### ISSUE THREAD

**Issue by uwuarkie** [TheonlyIcebear/Bloxflip-Smart-Bet#2]
Also after a few games in the probability based version the probability gets stuck on 99.9%.
The config I'm using is 
	"multiplier": 2.27,
	"preferred_chance": 75,
	"games_averaged": 30,
	"bet_amount": 3,

**Comment by TheonlyIcebear** [comment]
Streak based doesn't print a percentage. Make sure you update the file and make sure your running the correct file as well
