### ISSUE TITLE
instant crash bug

### ISSUE THREAD

**Issue by Liays-eng** [TheonlyIcebear/Bloxflip-Smart-Bet#26]
when it instantly crashes at x1.00 it doesn't bet the next round

**Comment by TheonlyIcebear** [comment]
This is a currently known bug and I've been trying to fix this for a while now but the issue is really hard and has to do with the nature of spam refreshing a chrome tab. Feel free to join the discord server

**Comment by TheonlyIcebear** [comment]
Fixed
