### ISSUE TITLE
randomly crashes

### ISSUE THREAD

**Issue by Liays-eng** [TheonlyIcebear/Bloxflip-Smart-Bet#27]
it says "Blocked by ddos protection. Solve the captcha to continue.", then closes after a couple seconds, I usually get this error when the game lasts a bit long (around x10 and more)

also i'm sorry for bothering u that much, and I cant copy the error file since its too long for github idk why

**Comment by TheonlyIcebear** [comment]
This isn't caused by the length of the games as when the program checks to see if it's been blocked it hasn't even started recording the games and their crashpoints yet.

**Comment by Liays-eng** [comment]
> This isn't caused by the length of the games as when the program checks to see if it's been blocked it hasn't even started recording the games and their crashpoints yet.

then whats the issue

**Comment by TheonlyIcebear** [comment]
I'm not sure

**Comment by TheonlyIcebear** [comment]
Can you send errors.txt
