### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LachanSPU** [TheonlyIcebear/Bloxflip-Smart-Bet#29]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): chromedriver.storage.googleapis.com:443
DEBUG:urllib3.connectionpool:https://chromedriver.storage.googleapis.com:443 "GET /LATEST_RELEASE HTTP/1.1" 200 13
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): chromedriver.storage.googleapis.com:443
DEBUG:urllib3.connectionpool:https://chromedriver.storage.googleapis.com:443 "GET /102.0.5005.61/chromedriver_win32.zip HTTP/1.1" 200 6369227
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"excludeSwitches": ["enable-logging"], "extensions": [], "args": []}}}, "desiredCapabilities": {"browserName": "chrome", "pageLoadStrategy": "normal", "goog:chromeOptions": {"excludeSwitches": ["enable-logging"], "extensions": [], "args": []}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:54506
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session HTTP/1.1" 200 789
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/url {"url": "https://bloxflip.com/crash"}
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session/c88753f008e8bc5dbc87e4ee11d3aa18/url HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/execute/sync {"script": "localStorage.setItem(\"_DO_NOT_SHARE_BLOXFLIP_TOKEN\", \"\")", "args": []}
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session/c88753f008e8bc5dbc87e4ee11d3aa18/execute/sync HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/execute/sync {"script": "window.location = window.location", "args": []}
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session/c88753f008e8bc5dbc87e4ee11d3aa18/execute/sync HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/elements {"using": "css selector", "value": ".MuiInputBase-input.MuiFilledInput-input.MuiInputBase-inputAdornedStart.MuiFilledInput-inputAdornedStart"}
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session/c88753f008e8bc5dbc87e4ee11d3aa18/elements HTTP/1.1" 200 169
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/element {"using": "css selector", "value": ".MuiBox-root.jss227.jss44"}
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session/c88753f008e8bc5dbc87e4ee11d3aa18/element HTTP/1.1" 404 1011
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/element {"using": "css selector", "value": ".MuiBox-root.jss220.jss44"}
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session/c88753f008e8bc5dbc87e4ee11d3aa18/element HTTP/1.1" 404 1011
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/element {"using": "css selector", "value": ".MuiBox-root.jss102.jss44"}
DEBUG:urllib3.connectionpool:http://localhost:54506 "POST /session/c88753f008e8bc5dbc87e4ee11d3aa18/element HTTP/1.1" 404 1011
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:DELETE http://localhost:54506/session/c88753f008e8bc5dbc87e4ee11d3aa18/window {}
DEBUG:urllib3.connectionpool:http://localhost:54506 "DELETE /session/c88753f008e8bc5dbc87e4ee11d3aa18/window HTTP/1.1" 200 12
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request

**Comment by TheonlyIcebear** [comment]
Whats the problem?

**Comment by LachanSPU** [comment]
> Whats the problem?

Well chrome closes after a few seconds and I don't have  a config file.

**Comment by TheonlyIcebear** [comment]
Download data.json
