### ISSUE TITLE
Exception has occurred: InvalidStatusCode X

### ISSUE THREAD

**Issue by SkorFury** [TheonlyIcebear/Bloxflip-Smart-Bet#3]
Whenever i run the script ProbabilityBased.py I get the error
![unknown](https://user-images.githubusercontent.com/73750434/161289461-e3364299-76c9-4bca-ade6-9fb2b6cf81e1.jpg)

This error is also at Callstack MainThread "server rejected WebSocket connection: HTTP 403"

**Comment by TheonlyIcebear** [comment]
Yup sadly bloxflip has blocked the program from connecting to their websockets. 403 means that the server blocked the request. I am not sure how to fix this as of now so for now the program is not functional

**Comment by SkorFury** [comment]
Oh okay

**Comment by Arisstath** [comment]
> Yup sadly bloxflip has blocked the program from connecting to their websockets. 403 means that the server blocked the request. I am not sure how to fix this as of now so for now the program is not functional

it's the ddos mitigation ruleset that is blocking your program

**Comment by TheonlyIcebear** [comment]
I have fixed with with the use of selenium now
