### ISSUE TITLE
got me cleaned. 5k to 0

### ISSUE THREAD

**Issue by RusstyCrussty123** [TheonlyIcebear/Bloxflip-Smart-Bet#33]
DO NOT USE THIS. IT LEGIT IS TERRIBLE AT BETTING. LOST ALL MY MONEY>

**Comment by TheonlyIcebear** [comment]
Oof sorry to hear that but gambling is random so it's not really the programs fault. Just the nature of gambling. You probably encountered a massive losing streak and got cleaned.

That's why I'm adding a function to stop the betamount from getting to high. Thanks for the feedback though
