### ISSUE TITLE
fastest way to lose money.

### ISSUE THREAD

**Issue by johnnyburglintin** [TheonlyIcebear/Bloxflip-Smart-Bet#34]
stopped it before it almost got me cleaned. dont download this

**Comment by TheonlyIcebear** [comment]
Sorry to hear that but gambling is random so it's not really the programs fault. Just the nature of gambling. You probably encountered a massive losing streak and got cleaned.

That's why I'm adding a function to stop the betamount from getting to high. Thanks for the feedback though
