### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SkorFury** [TheonlyIcebear/Bloxflip-Smart-Bet#5]
![unknown](https://user-images.githubusercontent.com/73750434/163681969-808105f2-0f43-4968-9487-9f8085361279.png)

There is also an error with **[ ERROR ] Blocked by ddos protection. If there's a captcha solve it.**
I don't have a vpn and there is no captcha.

**Comment by TheonlyIcebear** [comment]
Looking just a line a above it shows that there's a try and below that line there's a except. The error is caught by the program.
