### ISSUE TITLE
Error again

### ISSUE THREAD

**Issue by Alex2208231** [TheonlyIcebear/Bloxflip-Smart-Bet#50]
I get error after i did all the steps on the v1.2.5 version it gives me error that im on v1.2.4 which is impossible cause i'm sure i downloaded the last version v1.2.5
![Screenshot 2022-07-03 111513](https://user-images.githubusercontent.com/76810791/177031249-3306d01d-5ab8-4d98-b2d6-5c2d48f75982.png)

**Comment by TheonlyIcebear** [comment]
You may be using the exe's. In that case, don't 😂
