### ISSUE TITLE
Add Support for Major Chromium Based Browsers

### ISSUE THREAD

**Issue by SavageKiller13** [TheonlyIcebear/Bloxflip-Smart-Bet#53]
A good feature that would be useful and lower amount of useless bug reports (main error being: 'cannot find Chrome binary') would be support for other chromium based browsers. Looking into the documentation for the Selenium WebDriver, any browser that is based off of Chromium (two major ones being Opera and Microsoft Edge), can use the chromedriver packaged with the tool. 
As for implementing this, A simple config option for which browser to use will work. Then just adding a check for what browser is picked, and lastly setting the binary_location to where the specified browser is located.

**Comment by TheonlyIcebear** [comment]
This is a very good suggestion but program is seleniumless now so not very helpful now lol
