### ISSUE TITLE
Yo mine better

### ISSUE THREAD

**Issue by Athena-zip** [TheonlyIcebear/Bloxflip-Smart-Bet#54]

**Comment by TheonlyIcebear** [comment]
Yours is a virus 🤡

**Comment by Vxc4s** [comment]
BRO UR MULTITOOL DOESNT HAVE MAIN.PY WITH THE CODE.

**Comment by Rdmo1** [comment]
> BRO UR MULTITOOL DOESNT HAVE MAIN.PY WITH THE CODE.

I'm updating it , it will be released around 18 to 17
