### ISSUE TITLE
Autorain & Towers (Paid) Crashes and i've tryed redownloading everything

### ISSUE THREAD

**Issue by DeveloperVoid** [TheonlyIcebear/Bloxflip-Smart-Bet#57]
My Auto rain crashes and towers crashes this is the error code for towers 
ERROR:root:A error has occured at 01:48:01 01
Traceback (most recent call last):
  File "Towers (Paid).py", line 23, in __init__
  File "Towers (Paid).py", line 150, in getConfig
KeyError: 'tower_levels'

this is the error for auto rain
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 520 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.roblox.com:443
DEBUG:urllib3.connectionpool:https://api.roblox.com:443 "GET /users/get-by-username?username=wDynamic HTTP/1.1" 200 106
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 520 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rest-bf.blox.land:443
DEBUG:urllib3.connectionpool:https://rest-bf.blox.land:443 "GET /chat/history HTTP/1.1" 200 None

**Comment by TheonlyIcebear** [comment]
You've tried everything but redownloading the files? Your using the old config.json format.

**Comment by DeveloperVoid** [comment]
> You've tried everything but redownloading the files? Your using old code.

I have redownloaded it but I’m going to try the new version you just made now
