### ISSUE TITLE
I need help pls

### ISSUE THREAD

**Issue by ShojiKageyasu** [TheonlyIcebear/Bloxflip-Smart-Bet#58]
![908ae5c98f6be7e863d77afe9d2142e7](https://user-images.githubusercontent.com/111337591/184807446-7fd74eb6-f5a0-4b7f-b911-e0a1cd751fa8.png)

**Comment by ShojiKageyasu** [comment]
Also this
![828062bd0e97c65726ee963cea032f30](https://user-images.githubusercontent.com/111337591/184810119-9312ef9d-c8f2-44cb-a611-26d686b5792d.png)

**Comment by TheonlyIcebear** [comment]
The format of your json file is incorrect

**Comment by ShojiKageyasu** [comment]
How do i change it?
