### ISSUE TITLE
This happens everytime it tries betting

### ISSUE THREAD

**Issue by uwuarkie** [TheonlyIcebear/Bloxflip-Smart-Bet#6]
[untitled.txt](https://github.com/TheonlyIcebear/Bloxflip-Smart-Bet/files/8510698/untitled.txt)

**Comment by uwuarkie** [comment]
After that happens it stops and closes

**Comment by GitScrub123** [comment]
im getting the same issue

**Comment by TheonlyIcebear** [comment]
Make sure your logged and and I'm not really sure why this happens myself

**Comment by AstroOnYT** [comment]
it still happens bro just happened to me thats so annoying

**Comment by TheonlyIcebear** [comment]
I have fixed this now with some error handling.
