### ISSUE TITLE
webserver error

### ISSUE THREAD

**Issue by polarbeen** [TheonlyIcebear/Bloxflip-Smart-Bet#65]
this error only happening with martingale and martingale+predictor

![imagen](https://user-images.githubusercontent.com/73028283/185888560-c854d09c-ff5b-48a4-ba5f-acf4ade1d3c6.png)

**Comment by InsulatorGMan** [comment]
This was fixed an hour or so ago

**Comment by TheonlyIcebear** [comment]
Fixed
