### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by GitScrub123** [TheonlyIcebear/Bloxflip-Smart-Bet#7]
I get this error when trying to start the program (I already tried redownloading)

`[ ERROR ] Invalid data inside JSON file. Redownload from github`

**Comment by uwuarkie** [comment]
Did you edit your config?

**Comment by GitScrub123** [comment]
> Did you edit your config?

yes, I just added my auth token to "authorization"

**Comment by GitScrub123** [comment]
nvm i just fixed it. It was an error on my part.
